services:

  - type: psql
    name: petconnect-db
    plan: free 


  - type: web
    name: petconnect-api
    plan: free 
    env: docker

    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    healthCheck:
      path: /

    envVars:

      - from:
          type: psql
          name: petconnect-db
          property: connectionString
        to: DATABASE_URL
      - group: petconnect-secrets
        key: SECRET_KEY
      - group: petconnect-secrets
        key: ALGORITHM
      - group: petconnect-secrets
        key: ACCESS_TOKEN_EXPIRE_MINUTES


  - type: web
    name: petconnect-frontend
    plan: free
    env: docker

    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    build:
      args:
        VITE_API_URL: ${{services.petconnect-api.url}}