databases:
  - name: petconnect-db
    plan: free

services:
  - type: web
    name: petconnect-api
    plan: free
    env: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: petconnect-db
          property: connectionString
      - group: petconnect-secrets
        key: SECRET_KEY
      - group: petconnect-secrets
        key: ALGORITHM
      - group: petconnect-secrets
        key: ACCESS_TOKEN_EXPIRE_MINUTES

  - type: web
    name: petconnect-frontend
    plan: free
    env: docker
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    build:
      args:
        VITE_API_URL: ${{services.petconnect-api.url}}