# .github/workflows/ci.yml

name: PetConnect CI

on:
  push:
    branches:
      - "main"
      - "feature/**"
  
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: "a_secret_key_for_testing_purposes_only_123456"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      DATABASE_USER: "testuser"
      DATABASE_PASSWORD: "testpassword"
      DATABASE_NAME: "testdb"
      DATABASE_HOST: "localhost"
      DATABASE_PORT: 5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # CORREÇÃO: Aponta para o requirements.txt dentro da pasta backend
          pip install -r backend/requirements.txt

      - name: Run tests with pytest
        run: pytest --cov=backend/app --cov-fail-under=70